background = #1a150b
foreground = #dbd7cd
cursor-color = #faf8f3
selection-background = #413724
selection-foreground = #faf8f3

palette = 0=#1a150b
palette = 1=#9a664a
palette = 2=#7d8567
palette = 3=#897a57
palette = 4=#7d8569
palette = 5=#98674c
palette = 6=#7d8565
palette = 7=#dbd7cd
palette = 8=#636459
palette = 9=#bb7f5d
palette = 10=#97a17e
palette = 11=#a6956c
palette = 12=#97a180
palette = 13=#bd7e5a
palette = 14=#97a17c
palette = 15=#faf8f3
