-- Generated by Omagen. Window style: border=neon border_size=2 shape=soft spacing=airy depth=shadow active=frosted_balanced inactive=shadow_only.
local active_border_color = { colors = { "rgb(a36c4b)", "rgb(98674c)" }, angle = 0 }
local inactive_border_color = "rgb(7d7a72)"
if _omagen_border_angle_timer then _omagen_border_angle_timer:set_enabled(false) end
if _omagen_glitch_timer then _omagen_glitch_timer:set_enabled(false) end
if _omagen_glitch_cleanup then _omagen_glitch_cleanup() end
if _omagen_window_opacity_cleanup then _omagen_window_opacity_cleanup() end
if _omagen_window_opacity_rule then _omagen_window_opacity_rule:set_enabled(false) end
_omagen_glitch_burst = function() end
_omagen_window_opacity_handshake = function() end
local active_shadow_color = "rgba(a36c4bd0)"
local inactive_shadow_color = "rgba(7d7a7255)"
local active_glow_color = "rgba(a36c4bd0)"
local inactive_glow_color = "rgba(7d7a7235)"

hl.config({
  general = {
    col = { active_border = active_border_color, inactive_border = inactive_border_color },
    border_size = 2,
    gaps_in = 8, gaps_out = 14,
  },
  group = { col = { border_active = active_border_color, border_inactive = inactive_border_color }, },
  decoration = {
    rounding = 4, rounding_power = 3,
    active_opacity = 1.00,
    inactive_opacity = 1.00,
    shadow = { enabled = true, render_power = 3, range = 24, color = active_shadow_color, color_inactive = inactive_shadow_color },
    glow = { enabled = true, range = 16, render_power = 3, color = active_glow_color, color_inactive = inactive_glow_color },
    blur = { enabled = true, size = 18, passes = 3, ignore_opacity = true, new_optimizations = true },
  },
})

-- Blur the translucent Omagen Live Canvas layer surface.
hl.layer_rule({ name = "omagen-live-canvas-backdrop-blur", match = { namespace = "^omagen-live-canvas$" }, blur = true, blur_popups = true, ignore_alpha = 0.20 })
hl.curve("omagenPrecision", { type = "bezier", points = { { 0.22, 0.78 }, { 0.18, 1 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "omagenPrecision" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 3, bezier = "omagenPrecision", style = "popin 92%" })
hl.animation({ leaf = "windowsOut", enabled = false })
hl.animation({ leaf = "fadeIn", enabled = false })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 0.6, bezier = "omagenPrecision" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 3.4, bezier = "omagenPrecision" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.2, bezier = "omagenPrecision", style = "slidefade 12%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 1.2, bezier = "omagenPrecision", style = "fade" })
hl.animation({ leaf = "border", enabled = true, speed = 1.2, bezier = "quick" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 1.2, bezier = "quick" })
hl.animation({ leaf = "fadeShadow", enabled = true, speed = 1.2, bezier = "quick" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 1.2, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 1.2, bezier = "omagenPrecision" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 1.2, bezier = "omagenPrecision", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 0.8, bezier = "omagenPrecision", style = "fade" })

-- Per-window materialization: scoped entrance opacity, then restore user ownership.
_omagen_window_opacity_pending = _omagen_window_opacity_pending or {}
_omagen_window_opacity_rule = hl.window_rule({
  name = "omagen-window-materialization",
  match = { tag = "omagen-materializing" },
  opacity = "0.94 override 0.94 override 0.94 override",
})
local _omagen_window_opacity_release = function(selector)
  hl.dispatch(hl.dsp.window.tag({ tag = "-omagen-materializing", window = selector }))
end

_omagen_window_opacity_cleanup = function()
  for selector, timer in pairs(_omagen_window_opacity_pending) do
    if timer then timer:set_enabled(false) end
    _omagen_window_opacity_release(selector)
  end
  _omagen_window_opacity_pending = {}
end

_omagen_window_opacity_handshake = function(window)
  if not window or not window.address then return end
  local selector = "address:" .. tostring(window.address)
  if _omagen_window_opacity_pending[selector] then return end
  hl.dispatch(hl.dsp.window.tag({ tag = "+omagen-materializing", window = selector }))
  local timer
  timer = hl.timer(function()
    timer:set_enabled(false)
    _omagen_window_opacity_release(selector)
    _omagen_window_opacity_pending[selector] = nil
  end, { timeout = 110, type = "repeat" })
  _omagen_window_opacity_pending[selector] = timer
end
hl.on("window.open", function(window) _omagen_window_opacity_handshake(window) end)

-- Keep the accent gradient moving around the focused pane.
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "linear", style = "loop" })
local _omagen_border_angle = 0
_omagen_border_angle_timer = hl.timer(function()
  _omagen_border_angle = (_omagen_border_angle + 12.0000) % 360
  hl.config({ general = { col = { active_border = { colors = active_border_color.colors, angle = _omagen_border_angle } } } })
end, { timeout = 100, type = "repeat" })
