foreground #dbd7cd
background #1a150b
selection_foreground #faf8f3
selection_background #413724

cursor #faf8f3
cursor_text_color #1a150b

active_border_color #a36c4b
active_tab_background #a36c4b

color0 #1a150b
color1 #9a664a
color2 #7d8567
color3 #897a57
color4 #7d8569
color5 #98674c
color6 #7d8565
color7 #dbd7cd
color8 #636459
color9 #bb7f5d
color10 #97a17e
color11 #a6956c
color12 #97a180
color13 #bd7e5a
color14 #97a17c
color15 #faf8f3
